# **Análise Exploratória de Dados**

## Informações do conjunto de dados:

## Importação das bibliotecas

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

import warnings
warnings.filterwarnings('ignore')

## Carregando o conjunto de dados

In [2]:
df_avaliacoes = pd.read_csv('../data/raw/avaliacoes.csv')
df_clientes = pd.read_csv('../data/raw/clientes.csv')
df_geolocalizacao = pd.read_csv('../data/raw/geolocalizacao.csv')
df_itens_pedidos = pd.read_csv('../data/raw/itens_pedidos.csv')
df_pagamentos = pd.read_csv('../data/raw/pagamentos.csv')
df_pedidos = pd.read_csv('../data/raw/pedidos.csv')
df_produtos = pd.read_csv('../data/raw/produtos.csv')
df_tabela_auxiliar = pd.read_csv('../data/raw/tabela_auxiliar.csv')
df_vendedores = pd.read_csv('../data/raw/vendedores.csv')

## Entendendo o conjunto de dados

In [3]:
def resumo_tabelas(tabelas):
    for nome, tabela in tabelas.items():
        linhas, colunas = tabela.shape
        nulos = tabela.isnull().sum()
        nulos_total = nulos.sum()
        duplicatas = tabela.duplicated().sum()

        print(f'\n{"="*150}')
        print(f'  TABELA: {nome.upper()}')
        print(f'{"="*150}')
        print(f'  Linhas      : {linhas}')
        print(f'  Colunas     : {colunas}')
        print(f'  Nulos       : {nulos_total} ({round(nulos_total / (linhas * colunas) * 100, 1)}% do total)')
        print(f'  Duplicatas  : {duplicatas} ({round(duplicatas / linhas * 100, 1)}% das linhas)')

    
        if nulos_total > 0:
            print(f'\n  Nulos por coluna:')
            for col, qtd in nulos[nulos > 0].items():
                print(f'    • {col}: {qtd} ({round(qtd / linhas * 100, 1)}%)')
    
        print(f'  Colunas     : {list(tabela.columns)}')
    
        print(f'\n  Primeiras 5 linhas:')
        display(tabela.head(5))
        print(f'  Últimas 5 linhas:')
        display(tabela.tail(5))
        print(f'  5 linhas aleatórias:')
        display(tabela.sample(5))
        print(f'  Tipos de dados:')
        display(tabela.dtypes)
        print(f'  Memória utilizada por coluna:')
        display(tabela.memory_usage(deep=True))
        print()

In [4]:
tabelas = {
    'df_avaliacoes': df_avaliacoes,
    'df_clientes': df_clientes,
    'df_geolocalizacao': df_geolocalizacao,
    'df_itens_pedidos': df_itens_pedidos,
    'df_pagamentos': df_pagamentos,
    'df_pedidos': df_pedidos,
    'df_produtos': df_produtos,
    'df_tabela_auxiliar': df_tabela_auxiliar,
    'df_vendedores': df_vendedores
}

resumo_tabelas(tabelas)

======================================================================================================================================================
  TABELA: DF_AVALIACOES
======================================================================================================================================================
  Linhas      : 99224
  Colunas     : 7
  Nulos       : 145903 (21.0% do total)
  Duplicatas  : 0 (0.0% das linhas)

  Nulos por coluna:
    • review_comment_title: 87656 (88.3%)
    • review_comment_message: 58247 (58.7%)
  Colunas     : ['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

  Primeiras 5 linhas:

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

  Últimas 5 linhas:

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07 00:00:00,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09 00:00:00,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49

  5 linhas aleatórias:

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
23177,4b22cd1c2bd512c68303b15baee20a35,055b1b19fcb7ec836c23f44053344b20,3,NaN,NaN,2018-03-07 00:00:00,2018-03-10 01:14:24
25333,fcd703b062af1e987c194c0c05c11ff7,f15e15e34e647bdbf9b1d1a608d6518d,3,NaN,NaN,2018-05-09 00:00:00,2018-05-14 14:47:30
6649,81edbeb48d0efdd377cb007354f996ce,f222b3fc537088809c0a227ebac8c7ab,5,NaN,NaN,2017-09-01 00:00:00,2017-09-02 14:13:42
61854,d01c494f0f7d526364b3d68be178e0ac,d587d9ba27c8eab0ace515d0b3476d67,5,NaN,NaN,2018-05-17 00:00:00,2018-05-20 16:09:33
77641,3e5a72e76d4966132a74fa288f65e2db,dac39ed0abfc9b2092f74f36f5157a79,4,NaN,Show de loja,2018-01-10 00:00:00,2018-01-13 00:04:02

  Tipos de dados:

review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

  Memória utilizada por coluna:

Index                          132
review_id                  8037144
order_id                   8037144
review_score                793792
review_comment_title       3553146
review_comment_message     7109742
review_creation_date       6747232
review_answer_timestamp    6747232
dtype: int64

======================================================================================================================================================
  TABELA: DF_CLIENTES
======================================================================================================================================================
  Linhas      : 99441
  Colunas     : 5
  Nulos       : 0 (0.0% do total)
  Duplicatas  : 0 (0.0% das linhas)
  Colunas     : ['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

  Primeiras 5 linhas:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

  Últimas 5 linhas:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

  5 linhas aleatórias:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
49976,1e34d5f2f76b66a767e02d4fcd550847,0ad1d79346c3b98b517348ecbbadfbc6,9172,santo andre,SP
94310,787ce24878a10ba3edc37411f8a2dfff,9645b21c9729854b350d4f7c595f4037,8420,sao paulo,SP
92856,c8b11aa20558a5c5b2a042f47c83de09,622e7326e8ef9aa065b58c8879eb9a84,5541,sao paulo,SP
83223,2eb58edf4b8493e1430234d8aaf76e30,d0401aa66d5c33ae752ece32f8474d3c,20230,rio de janeiro,RJ
8540,182dc723d820aae1a351f75ab1f53451,b5bd39235b4e377d8a64f37f82ed93f0,36150,rio novo,MG

  Tipos de dados:

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

  Memória utilizada por coluna:

Index                           132
customer_id                 8054721
customer_unique_id          8054721
customer_zip_code_prefix     795528
customer_city               5901273
customer_state              5071491
dtype: int64

======================================================================================================================================================
  TABELA: DF_GEOLOCALIZACAO
======================================================================================================================================================
  Linhas      : 1000163
  Colunas     : 5
  Nulos       : 0 (0.0% do total)
  Duplicatas  : 261831 (26.2% das linhas)
  Colunas     : ['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

  Primeiras 5 linhas:

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

  Últimas 5 linhas:

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
1000158,99950,-28.068639,-52.010705,tapejara,RS
1000159,99900,-27.877125,-52.224882,getulio vargas,RS
1000160,99950,-28.071855,-52.014716,tapejara,RS
1000161,99980,-28.388932,-51.846871,david canabarro,RS
1000162,99950,-28.070104,-52.018658,tapejara,RS

  5 linhas aleatórias:

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
767318,66833,-1.330544,-48.442327,belem,PA
556865,30720,-19.917216,-43.969593,belo horizonte,MG
909060,88200,-27.236651,-48.621809,tijucas,SC
201507,8220,-23.537607,-46.470298,sao paulo,SP
546317,30180,-19.917580,-43.935869,belo horizonte,MG

  Tipos de dados:

geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

  Memória utilizada por coluna:

Index                               132
geolocation_zip_code_prefix     8001304
geolocation_lat                 8001304
geolocation_lng                 8001304
geolocation_city               61580270
geolocation_state              51008313
dtype: int64

======================================================================================================================================================
  TABELA: DF_ITENS_PEDIDOS
======================================================================================================================================================
  Linhas      : 112650
  Colunas     : 7
  Nulos       : 0 (0.0% do total)
  Duplicatas  : 0 (0.0% das linhas)
  Colunas     : ['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

  Primeiras 5 linhas:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

  Últimas 5 linhas:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

  5 linhas aleatórias:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
4478,0a18d00cb652fc5698d4e3c3e01e7da0,1,764292b2b0f73f77a0272be03fdd45f3,bd23da7354813347129d751591d1a6e2,2017-09-18 02:33:35,89.90,9.44
76582,ae51637de4a4424c759ab8b2c4279310,1,5999995b8f64d769dbc6f592b86d6f8a,c013e57c075a06e5b5c48ee03c525719,2018-07-23 00:05:32,36.99,14.57
104835,ee24e7d976a47cc46be7304fe5654ae9,1,6c50c87e36d8641d67fbcceed5cfec5e,6560211a19b47992c3666cc44a7e94c0,2018-08-02 10:24:28,55.00,7.65
103283,ea88ef80cceb79ad79ed25ed33d0b7d9,1,b3716b1e3576d3f2f246139d80c67d6a,4a3ca9315b744ce9f8e9374361493884,2018-05-15 10:57:05,41.80,12.79
42741,615881190acfd290a2122e6e4d6055c8,1,2028bf1b01cafb2d2b1901fca4083222,cc419e0650a3c5ba77189a1882b7556a,2018-01-23 17:31:07,56.99,15.15

  Tipos de dados:

order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

  Memória utilizada por coluna:

Index                      132
order_id               9124650
order_item_id           901200
product_id             9124650
seller_id              9124650
shipping_limit_date    7660200
price                   901200
freight_value           901200
dtype: int64

======================================================================================================================================================
  TABELA: DF_PAGAMENTOS
======================================================================================================================================================
  Linhas      : 103886
  Colunas     : 5
  Nulos       : 0 (0.0% do total)
  Duplicatas  : 0 (0.0% das linhas)
  Colunas     : ['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

  Primeiras 5 linhas:

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

  Últimas 5 linhas:

,order_id,payment_sequential,payment_type,payment_installments,payment_value
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

  5 linhas aleatórias:

,order_id,payment_sequential,payment_type,payment_installments,payment_value
61546,d8921ec6a676e398ec918a0cc755af21,1,credit_card,2,237.47
40000,fcd8b3a2ce5ad445e576820a3655052f,1,credit_card,6,63.37
72942,c0607dd794398507f4e1371ad2369b93,1,credit_card,4,242.52
10847,47733b097428ea5d3b5646c79fa6caaa,1,credit_card,3,30.85
79716,416f4d86856fe1ce4eece8bb4e38cdb6,1,credit_card,8,265.50

  Tipos de dados:

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

  Memória utilizada por coluna:

Index                       132
order_id                8414766
payment_sequential       831088
payment_type            6109611
payment_installments     831088
payment_value            831088
dtype: int64

======================================================================================================================================================
  TABELA: DF_PEDIDOS
======================================================================================================================================================
  Linhas      : 99441
  Colunas     : 8
  Nulos       : 4908 (0.6% do total)
  Duplicatas  : 0 (0.0% das linhas)

  Nulos por coluna:
    • order_approved_at: 160 (0.2%)
    • order_delivered_carrier_date: 1783 (1.8%)
    • order_delivered_customer_date: 2965 (3.0%)
  Colunas     : ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

  Primeiras 5 linhas:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

  Últimas 5 linhas:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

  5 linhas aleatórias:

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
8788,dbaaebf6a6e547abe2187a376dfc80cb,1bd39c947fcc7819aaf31c7f37b6d740,delivered,2017-07-30 11:41:46,2017-07-30 11:50:14,2017-08-02 19:19:56,2017-08-10 21:10:15,2017-08-22 00:00:00
59697,5976280bcb9e91bcff848a26a932af9e,2f902ecc9673532b130b276c7c5f572f,delivered,2017-07-21 16:27:42,2017-07-25 03:30:33,2017-07-26 03:07:42,2017-07-31 21:46:58,2017-08-10 00:00:00
93506,69602d7086bce76ef900a362fa5304d2,3ee0e8309e4c1f0baef48886dede4e75,delivered,2018-05-17 16:55:19,2018-05-18 00:37:31,2018-05-18 13:05:00,2018-06-05 22:37:49,2018-06-07 00:00:00
8804,18cc6945eeb0fac797b1e48e96bb7ad7,14b49d162cc1a8333aec3853db1812f5,delivered,2018-01-15 15:38:06,2018-01-15 15:50:53,2018-01-30 12:44:48,2018-02-01 17:35:42,2018-02-16 00:00:00
91872,b89d417b1ba9f8e416b9e333ffa01a93,864c3a5085d7d4e6c2153baaf6274cc1,delivered,2018-07-28 10:11:59,2018-07-28 10:25:11,2018-07-30 15:16:00,2018-08-03 21:08:35,2018-08-17 00:00:00

  Tipos de dados:

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

  Memória utilizada por coluna:

Index                                132
order_id                         8054721
customer_id                      8054721
order_status                     5765932
order_purchase_timestamp         6761988
order_approved_at                6756228
order_delivered_carrier_date     6697800
order_delivered_customer_date    6655248
order_estimated_delivery_date    6761988
dtype: int64

======================================================================================================================================================
  TABELA: DF_PRODUTOS
======================================================================================================================================================
  Linhas      : 32951
  Colunas     : 9
  Nulos       : 2448 (0.8% do total)
  Duplicatas  : 0 (0.0% das linhas)

  Nulos por coluna:
    • product_category_name: 610 (1.9%)
    • product_name_lenght: 610 (1.9%)
    • product_description_lenght: 610 (1.9%)
    • product_photos_qty: 610 (1.9%)
    • product_weight_g: 2 (0.0%)
    • product_length_cm: 2 (0.0%)
    • product_height_cm: 2 (0.0%)
    • product_width_cm: 2 (0.0%)
  Colunas     : ['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

  Primeiras 5 linhas:

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

  Últimas 5 linhas:

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

  5 linhas aleatórias:

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
1889,1aecdb5fa3add74e385f25c6c527a462,ferramentas_jardim,41.0,3544.0,1.0,16400.0,100.0,30.0,30.0
27043,fb43e2d63e76125c76c8f07c263e0bd4,eletrodomesticos,60.0,289.0,1.0,950.0,16.0,45.0,35.0
18492,f72b7888719ff77bf96e14bc97b64430,cama_mesa_banho,51.0,1076.0,3.0,9800.0,65.0,20.0,45.0
2515,ba2f091ca82d75e44ed38787ed180aa1,utilidades_domesticas,58.0,1137.0,1.0,19550.0,43.0,79.0,41.0
11097,c1d228e0eb297c790ce9981dac9c340a,automotivo,47.0,2116.0,1.0,1233.0,24.0,10.0,13.0

  Tipos de dados:

product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

  Memória utilizada por coluna:

Index                             132
product_id                    2669031
product_category_name         2088007
product_name_lenght            263608
product_description_lenght     263608
product_photos_qty             263608
product_weight_g               263608
product_length_cm              263608
product_height_cm              263608
product_width_cm               263608
dtype: int64

======================================================================================================================================================
  TABELA: DF_TABELA_AUXILIAR
======================================================================================================================================================
  Linhas      : 71
  Colunas     : 2
  Nulos       : 0 (0.0% do total)
  Duplicatas  : 0 (0.0% das linhas)
  Colunas     : ['product_category_name', 'product_category_name_english']

  Primeiras 5 linhas:

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

  Últimas 5 linhas:

            product_category_name product_category_name_english
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

  5 linhas aleatórias:

   product_category_name product_category_name_english
47         moveis_quarto             furniture_bedroom
6             perfumaria                     perfumery
10     alimentos_bebidas                    food_drink
15        telefonia_fixa               fixed_telephony
70    seguros_e_servicos         security_and_services

  Tipos de dados:

product_category_name            object
product_category_name_english    object
dtype: object

  Memória utilizada por coluna:

Index                             132
product_category_name            4684
product_category_name_english    4620
dtype: int64

======================================================================================================================================================
  TABELA: DF_VENDEDORES
======================================================================================================================================================
  Linhas      : 3095
  Colunas     : 4
  Nulos       : 0 (0.0% do total)
  Duplicatas  : 0 (0.0% das linhas)
  Colunas     : ['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

  Primeiras 5 linhas:

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

  Últimas 5 linhas:

,seller_id,seller_zip_code_prefix,seller_city,seller_state
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP

  5 linhas aleatórias:

,seller_id,seller_zip_code_prefix,seller_city,seller_state
1106,bdf0d02d36a1d839d0c39c4a887cdd49,16200,birigui,SP
409,085f6f7e049c996695fb2074fe38d45e,12020,taubate,SP
2966,70eea00b476a314817cefde4aad4f89a,13250,itatiba,SP
317,5acd070dd3fe441bbb2ec1f1ede515ee,13203,jundiai,SP
1368,954e95f20808d7e5d11f0de292d078e0,35930,joao monlevade,MG

  Tipos de dados:

seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

  Memória utilizada por coluna:

Index                        132
seller_id                 250695
seller_zip_code_prefix     24760
seller_city               183239
seller_state              157845
dtype: int64

## Tratamento dos tipos de dados|

In [5]:
df_avaliacoes = df_avaliacoes.astype({
    'review_id':'string',
    'order_id':'string',
    'review_score':'Int8',
    'review_comment_title':'string',
    'review_comment_message':'string',
})
for col in ['review_creation_date', 'review_answer_timestamp']:
    df_avaliacoes[col] = pd.to_datetime(df_avaliacoes[col])

df_clientes = df_clientes.astype({
    'customer_id':'string',
    'customer_unique_id':'string',
    'customer_zip_code_prefix':'string',
    'customer_city':'category',
    'customer_state':'category',
})


df_geolocalizacao = df_geolocalizacao.astype({
    'geolocation_zip_code_prefix':'string',
    'geolocation_lat':'float32',
    'geolocation_lng':'float32',
    'geolocation_city':'category',
    'geolocation_state':'category',
})

df_itens_pedidos = df_itens_pedidos.astype({
    'order_id':'string',
    'order_item_id':'Int64',
    'product_id':'string',
    'seller_id':'string',
    'price':'float32',
    'freight_value':'float32',
})
df_itens_pedidos['shipping_limit_date'] = pd.to_datetime(df_itens_pedidos['shipping_limit_date'])

df_pagamentos = df_pagamentos.astype({
    'order_id':'string',
    'payment_sequential':'Int8',
    'payment_type':'category',
    'payment_installments':'Int8',
    'payment_value':'float32',
})

df_pedidos = df_pedidos.astype({
    'order_id':'string',
    'customer_id':'string',
    'order_status':'category',
})
for col in [
    'order_purchase_timestamp',
    'order_approved_at',
    'order_delivered_carrier_date',
    'order_delivered_customer_date',
    'order_estimated_delivery_date',
]:
    df_pedidos[col] = pd.to_datetime(df_pedidos[col])

df_produtos = df_produtos.astype({
    'product_id':'string',
    'product_category_name':'category',
    'product_name_lenght':'Int16',
    'product_description_lenght':'Int32',
    'product_photos_qty':'Int8',
    'product_weight_g':'float32',
    'product_length_cm':'float32',
    'product_height_cm':'float32',
    'product_width_cm':'float32',
})

df_tabela_auxiliar = df_tabela_auxiliar.astype({
    'product_category_name':'category',
    'product_category_name_english':'category',
})

df_vendedores = df_vendedores.astype({
    'seller_id':'string',
    'seller_zip_code_prefix':'string',
    'seller_city':'category',
    'seller_state':'category',
})

Como o objetivo é entender a relação entre notas e comentários, vamos focar na tabela de avaliações.

## Tabela de avaliações

In [6]:
tabelas = {
    'df_avaliacoes': df_avaliacoes,
}

resumo_tabelas(tabelas)

======================================================================================================================================================
  TABELA: DF_AVALIACOES
======================================================================================================================================================
  Linhas      : 99224
  Colunas     : 7
  Nulos       : 145903 (21.0% do total)
  Duplicatas  : 0 (0.0% das linhas)

  Nulos por coluna:
    • review_comment_title: 87656 (88.3%)
    • review_comment_message: 58247 (58.7%)
  Colunas     : ['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

  Primeiras 5 linhas:

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,<NA>,<NA>,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,<NA>,<NA>,2018-03-10,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,<NA>,<NA>,2018-02-17,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,<NA>,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,<NA>,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53

  Últimas 5 linhas:

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,<NA>,<NA>,2018-07-07,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,<NA>,<NA>,2017-12-09,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,<NA>,"Excelente mochila, entrega super rápida. Super...",2018-03-22,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,<NA>,<NA>,2018-07-01,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,<NA>,"meu produto chegou e ja tenho que devolver, po...",2017-07-03,2017-07-03 21:01:49

  5 linhas aleatórias:

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
13091,a1632ef0a21095df47e3ec94b161decb,21740bea241f06ee46a7febe29061c31,1,<NA>,Estou indignada. É o presente de natal do eu f...,2017-12-21,2017-12-21 10:21:26
98958,233e6be9ddc54d7b45795025c0ab64dc,2343345152ce9ee61f54b2dae18561c1,5,super Recomendado,Entrega antes do prazo,2018-06-28,2018-06-28 17:47:29
7872,32915ca9df72e570048743cfb1473170,7bac976651f930dc34309b61897ce46c,5,<NA>,<NA>,2017-07-04,2017-07-07 00:21:52
97341,92abd52dbcd116327a141b99be05ea30,2af092d75759971722843fc88d8509a1,5,<NA>,Muito rapido,2018-05-12,2018-05-13 01:46:59
34593,9f471c3db6754ed57161289069f9d9d1,db5f60962b917b4dd9d73efd3e121ff6,2,<NA>,<NA>,2018-04-19,2018-04-25 21:00:16

  Tipos de dados:

review_id                  string[python]
order_id                   string[python]
review_score                         Int8
review_comment_title       string[python]
review_comment_message     string[python]
review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

  Memória utilizada por coluna:

Index                          132
review_id                  8037144
order_id                   8037144
review_score                198448
review_comment_title       5656890
review_comment_message     8507765
review_creation_date        793792
review_answer_timestamp     793792
dtype: int64

## Unindo as variáveis `review_comment_title` e `review_comment_message`

In [7]:
# unindo as variáveis `review_comment_title` e `review_comment_message` em uma nova coluna `review_comment_full`
df_avaliacoes['review_comment'] = df_avaliacoes['review_comment_title'].fillna('') + ' ' + df_avaliacoes['review_comment_message'].fillna('')

In [8]:
df_avaliacoes.sample(10)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,review_comment
41064,946fb3ef94920ffa150bb7e042ddf5c8,79186d3a09b1799222f2860be082e832,3,<NA>,<NA>,2018-01-25,2018-01-25 14:25:56,
55454,7be16824df28c8f84b5b778cad6d2757,2a70ce8b5ade3f0195fee5b3afc3bf71,5,<NA>,<NA>,2017-11-24,2017-11-27 01:28:58,
67037,3d02982f91553017416d6f4e961fc2ce,13a60be94bc36bf7c5f1e0a849cdd6e4,1,<NA>,"Problema com os correios, não realizou minha e...",2018-03-17,2018-03-19 11:16:54,"Problema com os correios, não realizou minha ..."
42789,023758ca275fb4fe7d134a87d99cbe01,1e4dc51447faa970879bb120932eebb6,5,<NA>,Depois que efetuei a compra. Fui informado apó...,2018-02-17,2018-04-12 14:24:40,Depois que efetuei a compra. Fui informado ap...
14851,0df75438a0abf8b317355dc1ffb5cfbd,2399e406198f0b9a12baf8e176453e9b,3,<NA>,<NA>,2018-03-31,2018-03-31 10:27:32,
72832,41e07f3b493983e6e0f209fe3dbddc45,51d837b72cf24883a9a18f061f382c2a,5,<NA>,"Chegou antes do praso previsto, recomendo.\r\n...",2018-01-18,2018-01-20 23:27:43,"Chegou antes do praso previsto, recomendo.\r\..."
33787,1b5f9bd4706842093846f599cbe8def6,462713cbc1abe1d91797604551133abf,5,Cabeceira linda!,Quero agradecer a loja por ter entregue bem an...,2018-08-18,2018-08-21 19:46:12,Cabeceira linda! Quero agradecer a loja por te...
68805,35db3efeb8b88fec9986a506a09cc703,9a17a8d78fe01948345e0beecbb3f879,5,<NA>,<NA>,2017-11-28,2017-11-30 00:11:50,
36607,95f39a6d088b7b7ac70f978fbcddf161,34984c4e45c628649f0e6c60a8f626f9,5,<NA>,<NA>,2018-06-02,2018-06-04 19:35:49,
71738,dd00e56a2d986ca4b42f672e941d66c5,94672e5686a487a37916262fab702f76,3,<NA>,<NA>,2018-02-02,2018-02-05 20:02:51,

## Removendo comentários vazios

In [9]:
df_avaliacoes_limpo = df_avaliacoes[df_avaliacoes['review_comment'] != ' ']

In [10]:
df_avaliacoes_limpo.sample(10)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,review_comment
76630,a13cd550dd016412ac1318e1990882ab,5a559395babb637d7999a5716873d882,1,<NA>,Ola. Ontem recebi meu Revoflex quebrado e falt...,2018-04-19,2018-04-19 18:26:05,Ola. Ontem recebi meu Revoflex quebrado e fal...
48399,8746a6150417f7cb4e628b3fd7c2bac6,f4ee4273538924bda6212f5948e80fde,5,Maravilha,Tudo perfeito,2018-06-26,2018-06-27 00:35:57,Maravilha Tudo perfeito
3764,021f2a15daad6d58a00422d72649bb25,b80ad2b6c5b351d9e15b84a8008a7d87,5,Bom loja,<NA>,2018-08-18,2018-08-18 21:53:41,Bom loja
74609,b1c18045cdea093ef77d2846e9b3c752,e4dbab8bc2ed64c1bfeb63cf0765c0c1,4,<NA>,Tudo certo,2018-03-17,2018-03-18 00:14:19,Tudo certo
48341,28b8de03073719ee531b07a5fe97228d,00fe20fc069833ab95021b46d6862646,5,Muito bom!,"Gente recebi meu relógio em 2 dias, muito rápi...",2018-04-28,2018-04-29 13:25:04,"Muito bom! Gente recebi meu relógio em 2 dias,..."
62759,b91ec4b047be78b2822cf8aaf61bf024,57a0aadef1c7db2296177ef296c89517,2,muito demorado,"Provavelmente evitarei comprar novamente, pois...",2018-05-22,2018-05-25 12:53:12,muito demorado Provavelmente evitarei comprar ...
43360,85044344a28408d8fc9224b1f597c8ec,2c039eca196d1a548fd739e82713a1b1,1,Eu quero meu produto,"Comprei a Garrafa térmica,E um kit de toalhas...",2018-08-24,2018-08-25 00:42:45,Eu quero meu produto Comprei a Garrafa térmic...
69696,3e2aef89dd5f1091a4215a93a529c8ae,4ea3c6eaf3dc15ad857675322bfb6bd0,4,Atenção,Ao comprar a panela elétric grill as fotos nos...,2018-08-30,2018-09-01 14:20:26,Atenção Ao comprar a panela elétric grill as f...
1410,e87a783c0914ab1bfbd4e45c9d7a1ae7,441162f9a6f1fb44588dea0f47eb713c,4,<NA>,Produto entregue antes do prazo. Bom custo ben...,2017-12-27,2017-12-28 01:01:26,Produto entregue antes do prazo. Bom custo be...
51226,d6e5e89b67501878d69448818b9e9e58,d5639d8a973cec351be75a3186835068,5,<NA>,Gostei e irei comprar mais,2017-11-25,2017-11-28 12:37:50,Gostei e irei comprar mais

## Removendo letras maiúsculas e pontuações

In [11]:
df_avaliacoes_limpo['review_comment'] = df_avaliacoes['review_comment'].str.lower()

In [12]:
import string

df_avaliacoes_limpo['review_comment'] = df_avaliacoes_limpo['review_comment'].str.translate(str.maketrans('', '', string.punctuation))

In [13]:
df_avaliacoes_limpo.sample(10)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,review_comment
7649,5cbfc758b5164e2e95ed1fe6c352aed9,28249398ab902fae0b07378e03da3729,2,<NA>,"Comprei 2 pneus, e a empresa despachou apenas ...",2017-12-07,2017-12-11 10:23:21,comprei 2 pneus e a empresa despachou apenas ...
13648,5d0a5fbed4f1cd5344cfa55d1078a839,d54365a56c5a4a3addc1eed046256f96,5,<NA>,Adorei perfeito e entregou n prazo,2018-03-20,2018-03-21 00:01:01,adorei perfeito e entregou n prazo
77818,ca3e385f2fbe56a6a5201f3bb8f9ddb5,c1da21318eac811a08b2bf209335c28b,5,Ótimo produto,Recomendo chegou antes do prazo,2018-08-01,2018-08-01 20:26:16,ótimo produto recomendo chegou antes do prazo
43386,e3957ab758dbb11657dd77005458beee,f4d52c8679d7de408090a7c7ec487cf3,5,<NA>,produto entregue rápido e conforme anunciado.....,2017-09-15,2017-09-18 10:07:16,produto entregue rápido e conforme anunciado\...
61734,a83011f37c427787c0f3b0a65984baaa,441596a9fde121f33c360d9c9ecae437,2,<NA>,"Esta super atrasados meu pedido,mais estão aco...",2018-04-13,2018-04-13 16:56:06,esta super atrasados meu pedidomais estão aco...
20147,17f7976d576d21f46cee1c28187a1eaf,dbd49fd0ab245be1d63d2e47ac959016,5,Satisfação,O produto é bom,2018-05-03,2018-05-03 23:56:08,satisfação o produto é bom
61529,5edc46de6751f0a5162597d2fe8c195f,707977c86502593ef9aa22201fbcbde5,1,<NA>,Não recebi ainda é prazo era dia 12 o que eu f...,2018-03-14,2018-03-15 03:09:31,não recebi ainda é prazo era dia 12 o que eu ...
19819,97046768f59f00a552ed3ef415188e9e,f8a6d03ed88e47a216d244f20d4333b4,1,Produto com defeito,Recebi o produto com defeito e estou aguardand...,2018-06-08,2018-06-11 12:47:44,produto com defeito recebi o produto com defei...
10267,1e1c893ea281b407367ea57440e1bcb4,796d7e38e13c7f6c4f227fb178fd58dc,1,<NA>,Meu tapete ainda não foi entregue.,2018-03-22,2018-03-23 00:12:15,meu tapete ainda não foi entregue
68551,722c41d55a65360608c0afb1c0882f32,d3cc9985b382ccfd773563453d506359,4,<NA>,Muito bom!,2017-04-23,2017-05-09 18:45:35,muito bom

## Removendo variáveis desnecessárias

In [14]:
avaliacoes = df_avaliacoes_limpo.copy()

avaliacoes = avaliacoes.drop(columns=['review_id', 'order_id', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp'])

In [15]:
avaliacoes.sample(10)

       review_score                                     review_comment
38653             1   faltam 3 lustres de minha compra veio apenas ...
2814              4   achei meio fraco mas conforme descrito vai se...
18831             3         visor do fone td arranhado unico problema
5298              5  entrega perfeita excelente produto entregue no...
26164             3   mas fiquei super chateada pq fiz um pedido co...
91964             5  compra excelente\r\nentrega rápida\r\nbem emba...
36703             5   ótima desde a compra até a entrega super rápi...
11925             3   faz um mês que espero e ainda não chegoupreci...
16581             5                               entrega super rápida
61178             5

## Exportando o conjunto de dados

In [16]:
# avaliacoes.to_parquet("avaliacoes.parquet", index=False)